version: '2'


services:
    nginx:
        image: eriweb/nginx-craft
        ports:
            - "80:80"
        volumes:
            - ./source:/app
        networks:
            - craft
        depends_on:
            - db
            - fpm

    fpm:
        image: eriweb/php7-fpm
        volumes:
            - ./source:/app
        networks:
            craft:
                aliases:
                    - php
        depends_on:
            - db
    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: 'craft'
        networks:
            craft:
                aliases:
                    - db

networks:
    craft: